# ----------------------------------------------------------------------------- #
# Welcome to your LinkMap configuration file.
#
# To personalize your page, simply edit the settings below and commit your
# changes. For more details, please see the README.md file.
# ----------------------------------------------------------------------------- #

# -- Main Content --
# These settings control the text and images that appear on your page.

title: Aditya S. Rathore | Link Hub
author_name: Aditya S. Rathore
description: "Product Manager | Software Engineer."
summary: "Builds 0-1 products with user-centric approach, was early engineer @Startup."
profile_picture_url: "assets/images/Headshot.png" # Optional: Add a URL or local path to an image.

# -- Appearance --
# These settings control the look and feel of your page.

skin: "dark" # Options: default, dark, mint, ocean, or your own custom skin.
button_style: "hard-shadow" # Options: filled, outline, hard-shadow
background_image: "/assets/images/background.jpg" # Optional: Add a URL or local path to an image.

# -- Links --
# These are the main buttons that will appear on your page.
# To add a new link, just copy the format.
main_links:
    - title: Explore My Portfolio
      url: http://adityasrathore.com
    - title: Book a 1:1 call
      url: https://app.reclaim.ai/m/aditya-s-rathore
    - title: View My Resume
      url: https://drive.google.com/drive/folders/1S7-XrgFijp-Jpd7bezqt1QFVx8VNaWlQ?usp=drive_link
    - title: Blog
      url: https://adigeak.github.io/

# -- Social Icons --
# These icons will appear under your tagline.
#
# 1. Find an icon at: https://fontawesome.com/v6/search?o=r&m=free
# 2. Set the 'icon_style' (e.g., "brands", "solid", "regular").
# 3. Set the 'icon_name' (e.g., "github", "link", "envelope").
social_links:
    - icon_style: "brands"
      icon_name: "youtube"
      url: "https://www.youtube.com/ @Aditya.S.Rathore"
    - icon_style: "brands"
      icon_name: "linkedin"
      url: "https://www.linkedin.com/in/aditya-s-rathore/"
    - icon_style: "brands"
      icon_name: "x-twitter"
      url: "https://x.com/adityasrathor3"
    - icon_style: "solid"
      icon_name: "globe"
      url: "https://adityasrathore.com/"

# -- Analytics --
# To enable analytics, set the 'provider' and fill in your ID or token.
analytics:
    provider: "mixpanel" # Options: false, "google", "mixpanel", "both"
    providers:
        google:
            tracking_id: "" # e.g., G-XXXXXXXXXX
        mixpanel:
            token: "1d2f2124417dcd370b95ab08328bfde5" # e.g., "YOUR_MIXPANEL_TOKEN"

# Required for GitHub Pages. Do not change.
plugins:
    - jekyll-seo-tag

# Sass settings
sass:
    sass_dir: _sass
